version: '2'
services:
    act-mysql:
        container_name: act-mysql
        image: mysql
        # volumes:
        #     - act-app-data/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=act
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl